### ISSUE TITLE
 What is new in DataFrames.jl - release highlights | Bogumił Kamiński | JuliaCon 2023 

### ISSUE THREAD

**Issue by Antoinemarteau** [JuliaCommunity/YouTubeVideoTimestamps#268] opened 2023-10-04 19:55 UTC
Hi, another proposition

References:
Speaker: Bogumił Kamiński
Video title: What is new in DataFrames.jl - release highlights | Bogumił Kamiński | JuliaCon 2023
Link: https://www.youtube.com/watch?v=YZRRrJrdod8

Contents
0:00 Welcome
0:06 Introduction
1:17 Creating a DataFrame from a CSV file
1:54 Mutating a DataFrame to sort its rows
3:44 Visualizing data using a regression and plotting
4:22 Comments on DataFrames' pace of development
8:44 DataFrames' evolution, what has changed since last JuliaCon ?
9:05 Breaking changes
11:42 New functionalities
16:29 On the "Jula for Data Analysis" book
17:49 Perspectives
18:42 Conclusion
19:00 Questions

**Comment by KZiemian** [comment] 2023-12-29 18:15
A little bit tweaked version of your work.

Contents
00:00 Opening and introduction
01:17 Creating a DataFrame from a CSV file
01:54 Mutating a DataFrame to sort its rows
03:44 Visualizing data using a regression and plotting
04:22 Comments on DataFrames' pace of development
08:44 DataFrames' evolution, what has changed since last JuliaCon?
09:05 Breaking changes
11:42 New functionalities
16:29 On the "Julia for Data Analysis" book
17:49 Perspectives
18:42 Conclusion
19:00 Questions

**Comment by KZiemian** [comment] 2024-01-12 18:11
Thank you. Timestamps were added to the video, we will close this issue, when we get access rights to this GitHub repository.

**Comment by KZiemian** [comment] 2024-01-16 13:00
It seems that everything is working well, so we close this issue.

**Closed as completed by KZiemian** 2024-01-16 13:00 UTC
